version: '3.8'

services:
  redis:
    image: redis:alpine
    container_name: mastery-redis
    ports:
      - "6379:6379"
    restart: always

  mysql:
    image: mysql:8.0
    container_name: mastery-mysql
    environment:
      MYSQL_ROOT_PASSWORD: pass123
      MYSQL_DATABASE: mastery_db
      MYSQL_USER: saurav
      MYSQL_PASSWORD: pass123
    ports:
      - "3305:3306" # Connect local 3305 to container 3306
    volumes:
      - mysql_mastery_data:/var/lib/mysql
    restart: always

volumes:
  mysql_mastery_data: